// models/Message.js
const mongoose = require("mongoose");

const MessageSchema = new mongoose.Schema(
  {
    conversationId: { type: mongoose.Schema.Types.ObjectId, ref: "Conversation", index: true, required: true },
    from: { type: mongoose.Schema.Types.ObjectId, ref: "User", index: true, required: true },
    to: { type: mongoose.Schema.Types.ObjectId, ref: "User", index: true, required: true },

    type: { type: String, enum: ["text", "image", "video", "file"], default: "text" },
    text: { type: String, default: "" },
    mediaUrl: { type: String, default: "" },

    clientId: { type: String, required: true }, // generated by app (uuid) for dedupe
    status: { type: String, enum: ["sent", "delivered", "read"], default: "sent" },

    deliveredAt: { type: Date, default: null },
    readAt: { type: Date, default: null },
  },
  { timestamps: true }
);

// fast pagination
MessageSchema.index({ conversationId: 1, createdAt: -1 });
// dedupe (very important for retries)
MessageSchema.index({ conversationId: 1, clientId: 1 }, { unique: true });

module.exports = mongoose.model("Message", MessageSchema);
